### PR TITLE
EUPS packaging and bin/firefly (tickets/dm-2731-eups-for-firefly)

### PR DESCRIPTION
**Pull request by mjuric**
Add packaging files for EUPS build and distribution system, and a script -- bin/firefly -- designed to be invoked by the end-user to start firefly as a desktop-style application. The packaging depends on gradle, Tomcat, and node.js (all EUPS packages as well, currently available at http://github.com/eupsforge).

Once the 'firefly' executable is run (it's in bin/, and EUPS' setup will add $FIREFLY_DIR/bin to the path), it will start Tomcat with the fftools webapp on a randomly chosen port.  It will print out the port on which it's running, and the browser may be pointed there (or, alternatively, the Python wrappers could in the future parse the result to communicate with the backend).

If one wants to define the ports instead of having them chosen at random (useful when debugging, or when not working on a shared machine), define the FFPORTS environmental variable, e.g.:
```
FFPORTS="8080 8005" firefly
```
The http server will run on the first port, and the second port is the "control" (aka shutdown) port.

Implementation: Firefly installed via EUPS builds the webapp and installs the .war file, the unpacked webapp, and the 'bin/firefly' script into its install directory.  Every time the bin/firefly script is run it will create a custom (throwaway) CATALINA_BASE directory (in $TMPDIR) into which it links the unpacked webapp.  It then starts Tomcat with the randomly chosen ports.  That allows the Firefly and Tomcat EUPS-controlled install directories to be read-only, while enabling having multiple instances of Tomcat running on the same machine, and running the same app, w/o collisions.

Running "in-tree": firefly script will detect when it's run from the source directory (i.e., in the directory that was cloned with git).  Instead of creating a throwaway CATALINA_BASE, it will use the one in './tomcat' subdirectory.  That directory has the .war file linked to ../../build/libs, so it will automatically pick it up any time its rebuild. This should enable this type of edit-build-test loop:
```
gradle :fftools:war   # build the library

firefly &   # Start firefly
... connect to it in the web browser, or otherwise ...

... make some changes to the source code ...
gradle :fftools:war  # rebuild
```
Note: Tomcat should automatically detect that the war changed and restart the webapp.

### CODE REVIEW

**Comment by robyww** [comment]
It appears that the java & node dependencies in http://github.com/eupsforge will only support Linux java & node. How does that work on other platforms?

**Comment by robyww** [comment]
I am concerned about generating random tomcat ports by default.  To anyone who has been around tomcat, 8080 is much the way we think of port 80 for http.  I see that having random ports is nice on a shared machine, but laptop or desktop environment it does not make sense.  Can we make the default to be 8080 and override it in the shared machine case?

**Comment by robyww** [comment]
Another shared machine concern.  On a shared machine it would we much, much better to have one tomcat server configure with a lot of memory instead of many with a little.  Firefly is made to be multi-user. Is there are way to make one shared firefly installation on a shared machine?  I think this get into the issues of services vs libraries.  Might be similar to having one dbms verse many on a machine.

**Comment by loitly** [comment]
A few suggestions:

User CATALINA_PID option when starting up Tomcat.  This allow for -force shutdown to ensure a clean shutdown.
	Set CATALINA_PID="$CATALINA_BASE/conf/catalina.pid" before catalina.sh start
	Use "catalina.sh stop n -force" to shutdown.  n is number of seconds.  defaults to 5 if not given.

Remove or comments out port 8009.  It is not needed and will generate error or warning when multiple instances are running.

An easy way to control JVM runtime option.  More specifically max heapsize(-Xmx)

Tomcat comes with a manager application.  It's good and simple way to examine the health of Tomcat.
	Just a suggestion.  It's perfectly okay to not include it.

**Comment by loitly** [comment]
firefly/tomcat:

Creating a temporary $CATALINA_BASE directory is a good idea.  Why not do that every time
instead of defaulting to firefly/tomcat.
This way firefly/tomcat does not need to be in git.  You can still default $CATALINA_BASE to it if you like.

It's easy to create $CATALINA_BASE from $CATALINA_HOME.
Instead of using firefly/tomcat/conf, you can copy /conf from $CATALINA_HOME replacing only server.xml.
server.xml can be moved into firefly/config/tomcat.

$CATALINA_BASE/webapps does not need to be symlinked.  
During firefly build, you can deploy it via a "deploy" target or by copying the war file into $CATALINA_BASE/webapps.
Tomcat will automatically expand and redeploy it.

**Comment by mjuric** [comment]
@robyww @loitly @RobertLuptonTheGood I rebased to the top of current master and added some fixes that Trey and Loi requested:

* Re ports: I still left them default to random, as I worry that the general public is very likely to run two firefly instances and not realize that there's a ports collision. I did add a '-p' option, which will by default set the ports to 8080,8004, or to a different pair when invoked with an argument as '-p httpPort,shutdownPort'. Probably the right thing to do here may be not to even start two instances, but just return if one is already running (but I'd leave this for a new ticket)?
* I'm now setting CATALINA_PID (thanks for the pointer!)
* I've commented out the 8009 port service

Re why not construct CATALINA_BASE from CATALINA_HOME on the fly -- I've thought about it, but decided against it because it's hard to know what will be in the user's $CATALINA_HOME (e.g., has the user customized their installation somehow?).

Hope this is good enough to be merged, and then you can continue improving it on master.

**Pull request merged**
